### ISSUE TITLE
Program not working

### ISSUE THREAD

**Issue by ukos-git** [chaxor/Spectro#2]
Loading of the example files worked.

Pressing Process Spectra produces output to the bottom window but no statistics are shown on the right window. System is debian8 but should be system independent.
![screenshot from 2017-01-19 19 18 28](https://cloud.githubusercontent.com/assets/16167358/22119488/1c0dc6ae-de7c-11e6-984e-43cea6d2b90b.png)

Full Output is
```
Gtk-Message: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "./Spectro.py", line 617, in deconvolute
    x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
    return function(*(wrapper_args + args))
  File "./Spectro.py", line 672, in residual
    residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "./Spectro.py", line 617, in deconvolute
    x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
    return function(*(wrapper_args + args))
  File "./Spectro.py", line 672, in residual
    residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "./Spectro.py", line 617, in deconvolute
    x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
    return function(*(wrapper_args + args))
  File "./Spectro.py", line 672, in residual
    residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "./Spectro.py", line 617, in deconvolute
    x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
    return function(*(wrapper_args + args))
  File "./Spectro.py", line 672, in residual
    residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "./Spectro.py", line 617, in deconvolute
    x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
    return function(*(wrapper_args + args))
  File "./Spectro.py", line 672, in residual
    residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "./Spectro.py", line 617, in deconvolute
    x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
    return function(*(wrapper_args + args))
  File "./Spectro.py", line 672, in residual
    residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "./Spectro.py", line 617, in deconvolute
    x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
    return function(*(wrapper_args + args))
  File "./Spectro.py", line 672, in residual
    residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "./Spectro.py", line 617, in deconvolute
    x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
    return function(*(wrapper_args + args))
  File "./Spectro.py", line 672, in residual
    residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "./Spectro.py", line 617, in deconvolute
    x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
    return function(*(wrapper_args + args))
  File "./Spectro.py", line 672, in residual
    residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "./Spectro.py", line 617, in deconvolute
    x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
    return function(*(wrapper_args + args))
  File "./Spectro.py", line 672, in residual
    residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "./Spectro.py", line 617, in deconvolute
    x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
    return function(*(wrapper_args + args))
  File "./Spectro.py", line 672, in residual
    residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "./Spectro.py", line 617, in deconvolute
    x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
    return function(*(wrapper_args + args))
  File "./Spectro.py", line 672, in residual
    residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
Traceback (most recent call last):
  File "./Spectro.py", line 617, in deconvolute
  File "./Spectro.py", line 617, in deconvolute
        x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
        **opts)
**opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
        f, g = func_and_grad(x)
f, g = func_and_grad(x)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
        f = fun(x, *args)
f = fun(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
        return function(*(wrapper_args + args))
return function(*(wrapper_args + args))
  File "./Spectro.py", line 672, in residual
  File "./Spectro.py", line 672, in residual
        residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
ValueErrorValueError: : setting an array element with a sequence.
setting an array element with a sequence.
Traceback (most recent call last):
Traceback (most recent call last):
  File "./Spectro.py", line 617, in deconvolute
  File "./Spectro.py", line 617, in deconvolute
        x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
x, f, d = scipy.optimize.fmin_l_bfgs_b(func = self.residual, x0=self.bkg_soln, bounds=self.bkg_soln_bounds, approx_grad = True, factr = 10)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 186, in fmin_l_bfgs_b
        **opts)
**opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 314, in _minimize_lbfgsb
        f, g = func_and_grad(x)
f, g = func_and_grad(x)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 260, in func_and_grad
        f = fun(x, *args)
f = fun(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
        return function(*(wrapper_args + args))
return function(*(wrapper_args + args))
  File "./Spectro.py", line 672, in residual
  File "./Spectro.py", line 672, in residual
        residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
residual_array[x_index] = temp_model[x_index] - self.Y[x_index]
ValueErrorValueError: : setting an array element with a sequence.
setting an array element with a sequence.
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running

```

**Comment by ukos-git** [comment]
considering  the low impact and overly long issues of this project, it can probably be considered dead. #1 #2
